"""empty message

Revision ID: 15431d352560
Revises: 
Create Date: 2024-12-31 03:10:53.185619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15431d352560'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('secondname', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'MODERATOR', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('issues',
    sa.Column('issue_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'FINALLY', name='statusenum'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priorityenum'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_table('proposals',
    sa.Column('proposal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'FINALLY', name='statusenum'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priorityenum'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('proposal_id')
    )
    op.create_table('votes',
    sa.Column('vote_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.Enum('YES', 'NO', name='voteenum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('vote_id')
    )
    op.create_table('archive',
    sa.Column('archive_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('archive_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.issue_id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.proposal_id'], ),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.vote_id'], ),
    sa.PrimaryKeyConstraint('archive_id')
    )
    op.create_table('moderation',
    sa.Column('moderation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('moderator_id', sa.Integer(), nullable=False),
    sa.Column('moderation_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'NONSUCCESS', name='moderationstatusenum'), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.issue_id'], ),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.proposal_id'], ),
    sa.PrimaryKeyConstraint('moderation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moderation')
    op.drop_table('archive')
    op.drop_table('votes')
    op.drop_table('proposals')
    op.drop_table('issues')
    op.drop_table('users')
    op.drop_table('category')
    # ### end Alembic commands ###
